# Generated by Django 5.0.4 on 2026-05-03 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(verbose_name='Enunciado de la pregunta')),
                ('respuesta_correcta', models.CharField(max_length=500, verbose_name='Respuesta correcta')),
                ('respuesta_usuario', models.CharField(blank=True, default='', max_length=500, verbose_name='Respuesta del estudiante')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Respuesta correcta?')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntaje obtenido')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de respuesta')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SesionDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Puntaje total')),
                ('nivel_asignado', models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='', max_length=20, verbose_name='Nivel asignado')),
                ('total_preguntas', models.PositiveIntegerField(default=0, verbose_name='Total de preguntas')),
                ('respuestas_correctas', models.PositiveIntegerField(default=0, verbose_name='Respuestas correctas')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('completado', models.BooleanField(default=False, verbose_name='Completado')),
            ],
            options={
                'verbose_name': 'Sesión de diagnóstico',
                'verbose_name_plural': 'Sesiones de diagnóstico',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
