# Generated by Django 5.0.4 on 2026-05-03 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='sesiondiagnostico',
            name='diagnosticos',
            field=models.ManyToManyField(blank=True, to='diagnostico.diagnostico', verbose_name='Preguntas respondidas'),
        ),
        migrations.AddField(
            model_name='sesiondiagnostico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_diagnostico', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
    ]
