# Generated by Django 5.0.4 on 2026-06-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoadmapLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Bloqueado"),
                            ("available", "Disponible"),
                            ("completed", "Completado"),
                        ],
                        default="locked",
                        max_length=10,
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=10)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("medium", "Medio"),
                            ("hard", "Difícil"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapQuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("options", models.TextField(help_text="Separadas por |")),
                ("correct_idx", models.PositiveIntegerField()),
                ("explanation", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("icon", models.CharField(default="⭐", max_length=10)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("medium", "Medio"),
                            ("hard", "Difícil"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("input_data", models.TextField()),
                ("expected", models.TextField()),
                ("is_hidden", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapUserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("solved", models.BooleanField(default=False)),
                ("xp_earned", models.PositiveIntegerField(default=0)),
                ("time_spent", models.PositiveIntegerField(default=0)),
                ("last_code", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoadmapUserXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                ("last_active", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoadmapExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("hint", models.TextField(blank=True)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("code", "Código Python"),
                            ("fill", "Completar blancos"),
                            ("quiz", "Opción múltiple"),
                        ],
                        default="code",
                        max_length=10,
                    ),
                ),
                (
                    "starter_code",
                    models.TextField(
                        blank=True, default="# Escribe tu solución aquí\n"
                    ),
                ),
                ("fill_template", models.TextField(blank=True)),
                (
                    "fill_answers",
                    models.TextField(blank=True, help_text="Separadas por |"),
                ),
                ("time_limit_secs", models.PositiveIntegerField(default=300)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("xp_reward", models.PositiveIntegerField(default=25)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("medium", "Medio"),
                            ("hard", "Difícil"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="roadmap.roadmaplesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapLessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Bloqueado"),
                            ("available", "Disponible"),
                            ("completed", "Completado"),
                        ],
                        default="locked",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.roadmaplesson",
                    ),
                ),
            ],
        ),
    ]
