# Generated by Django 5.0.4 on 2026-05-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmaplesson",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Fácil"), ("medium", "Medio"), ("hard", "Difícil")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="roadmapstage",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Fácil"), ("medium", "Medio"), ("hard", "Difícil")],
                default="easy",
                max_length=10,
            ),
        ),
    ]
