# Generated by Django 5.0.4 on 2026-06-17 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=150, verbose_name="Apellido")),
                ("es_activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("es_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de registro",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("estudiante", "Estudiante"),
                            ("profesor", "Profesor"),
                        ],
                        default="estudiante",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("usuarios.usuario",),
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[],
            options={
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("usuarios.usuario",),
        ),
        migrations.CreateModel(
            name="PerfilEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_actual",
                    models.PositiveIntegerField(
                        choices=[(1, "easy"), (2, "medium"), (3, "hard")],
                        default=1,
                        verbose_name="Nivel actual",
                    ),
                ),
                (
                    "progreso",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        limit_choices_to={"rol": "estudiante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_estudiante",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de estudiante",
                "verbose_name_plural": "Perfiles de estudiantes",
            },
        ),
        migrations.CreateModel(
            name="PerfilProfesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        limit_choices_to={"rol": "profesor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_profesor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de profesor",
                "verbose_name_plural": "Perfiles de profesores",
            },
        ),
    ]
