# Generated by Django 5.0.4 on 2026-05-09 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("usuarios.usuario",),
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[],
            options={
                "verbose_name": "Profesor",
                "verbose_name_plural": "Profesores",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("usuarios.usuario",),
        ),
        migrations.AddField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[("estudiante", "Estudiante"), ("profesor", "Profesor")],
                default="estudiante",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
        migrations.CreateModel(
            name="PerfilEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel_actual",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Principiante"),
                            (2, "Intermedio"),
                            (3, "Avanzado"),
                            (4, "Experto"),
                            (5, "Maestro"),
                        ],
                        default=1,
                        verbose_name="Nivel actual",
                    ),
                ),
                (
                    "progreso",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Progreso (%)",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        limit_choices_to={"rol": "estudiante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_estudiante",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de estudiante",
                "verbose_name_plural": "Perfiles de estudiantes",
            },
        ),
        migrations.CreateModel(
            name="PerfilProfesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        limit_choices_to={"rol": "profesor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_profesor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de profesor",
                "verbose_name_plural": "Perfiles de profesores",
            },
        ),
    ]
