# Generated by Django 5.0.4 on 2026-05-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_estudiante_profesor_usuario_rol_perfilestudiante_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilestudiante",
            name="nivel_actual",
            field=models.PositiveIntegerField(
                choices=[(1, "Principiante"), (2, "Intermedio"), (3, "Avanzado")],
                default=1,
                verbose_name="Nivel actual",
            ),
        ),
    ]
