# Generated by Django 5.0.4 on 2026-06-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_perfilestudiante_nivel_actual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilestudiante",
            name="nivel_actual",
            field=models.PositiveIntegerField(
                choices=[(1, "easy"), (2, "medium"), (3, "hard")],
                default=1,
                verbose_name="Nivel actual",
            ),
        ),
    ]
